include:
  - "http://download.repo.tds/ci/templates-build.yml"
  - "http://download.repo.tds/ci/templates-upload.yml"
  - "http://download.repo.tds/ci/templates-servers-task.yml"

stages:
  - build-dev
  - publish-dev
  - build-prod
  - publish-prod

build-dev-arch:
  extends: .build_dev_python_arch
  stage: build-dev
  variables:
    IMAGE_PATH: "archlinux:generic-python-builder"
  allow_failure: true

publish-dev-arch:
  extends: .publish_dev_arch_pkg
  stage: publish-dev
  dependencies:
    - build-dev-arch

build-prod-arch:
  extends: .build_prod_python_arch
  stage: build-prod
  variables:
    IMAGE_PATH: "archlinux:generic-python-builder"
  allow_failure: true

publish-prod-arch:
  extends: .publish_stage_arch_pkg
  stage: publish-prod
  script:
    - curl -f -X POST -F "package=@`ls build/arch/*.pkg.tar.xz`" "http://mandragora-${REPO_ENV}.repo.tds/custom/upload?res_deps="
  variables:
    REPO_ENV: dev
  dependencies:
    - build-dev-arch
