include:
  - "http://download.repo.tds/ci/templates-build.yml"
  - "http://download.repo.tds/ci/templates-upload.yml"
  - "http://download.repo.tds/ci/templates-servers-task.yml"

stages:
  - build-dev
  - publish-dev
  - build-prod
  - publish-prod

build-dev-arch:
  extends: .build_dev_python_arch
  stage: build-dev
  variables:
    IMAGE_PATH: "archlinux:teldrassil"
  allow_failure: true

publish-dev-arch:
  extends: .publish_dev_arch_pkg
  stage: publish-dev
  variables:
    GIT_STRATEGY: none
    REPO_ENV: infra-dev
    REPO_NAME: custom
  dependencies:
    - build-dev-arch

build-prod-arch:
  extends: .build_prod_python_arch
  stage: build-prod
  variables:
    IMAGE_PATH: "archlinux:teldrassil"
  allow_failure: true

publish-prod-arch:
  extends: .publish_stage_arch_pkg
  stage: publish-prod
  variables:
    GIT_STRATEGY: none
    REPO_ENV: infra-prod
    REPO_NAME: custom
  dependencies:
    - build-prod-arch
