"""empty message

Revision ID: 1fbc0b1916a6
Revises: 2b3b6b1f616d
Create Date: 2020-06-12 14:10:14.787847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbc0b1916a6'
down_revision = '2b3b6b1f616d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
