"""empty message

Revision ID: 29c74f8a5743
Revises: 4e91f897719b
Create Date: 2020-06-10 16:11:04.496139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c74f8a5743'
down_revision = '4e91f897719b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('authorized_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'authorized_at')
    # ### end Alembic commands ###
