"""empty message

Revision ID: 2b3b6b1f616d
Revises: 8fdcc15c2cda
Create Date: 2020-06-12 13:59:12.912744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3b6b1f616d'
down_revision = '8fdcc15c2cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'token')
    # ### end Alembic commands ###
