"""empty message

Revision ID: 4e91f897719b
Revises: d6bf740b1adf
Create Date: 2020-06-10 16:02:51.090827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e91f897719b'
down_revision = 'd6bf740b1adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_token_id'), 'tokens', ['token_id'], unique=True)
    op.drop_index('ix_users_public_id', table_name='users')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=True)
    op.drop_index(op.f('ix_tokens_token_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
