"""empty message

Revision ID: 8fdcc15c2cda
Revises: cba6193fcdeb
Create Date: 2020-06-11 15:26:02.770416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdcc15c2cda'
down_revision = 'cba6193fcdeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_tokens', sa.Column('token_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_blacklisted_tokens_token_id'), 'blacklisted_tokens', ['token_id'], unique=True)
    op.drop_index('ix_blacklisted_tokens_blacklisted_token_id', table_name='blacklisted_tokens')
    op.drop_column('blacklisted_tokens', 'blacklisted_token_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_tokens', sa.Column('blacklisted_token_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index('ix_blacklisted_tokens_blacklisted_token_id', 'blacklisted_tokens', ['blacklisted_token_id'], unique=True)
    op.drop_index(op.f('ix_blacklisted_tokens_token_id'), table_name='blacklisted_tokens')
    op.drop_column('blacklisted_tokens', 'token_id')
    # ### end Alembic commands ###
