"""empty message

Revision ID: d4d768064e26
Revises: 6fb31e18c8e5
Create Date: 2020-06-10 12:14:14.219779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4d768064e26'
down_revision = '6fb31e18c8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.alter_column('blacklisted_tokens', 'token_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_blacklisted_tokens_token_id'), 'blacklisted_tokens', ['token_id'], unique=True)
    op.drop_constraint('blacklisted_tokens_token_id_fkey', 'blacklisted_tokens', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('blacklisted_tokens_token_id_fkey', 'blacklisted_tokens', 'tokens', ['token_id'], ['id'])
    op.drop_index(op.f('ix_blacklisted_tokens_token_id'), table_name='blacklisted_tokens')
    op.alter_column('blacklisted_tokens', 'token_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('tokens',
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('read_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('write_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey'),
    sa.UniqueConstraint('token', name='tokens_token_key')
    )
    # ### end Alembic commands ###
