"""empty message

Revision ID: d6bf740b1adf
Revises: d4d768064e26
Create Date: 2020-06-10 12:21:35.807344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bf740b1adf'
down_revision = 'd4d768064e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklisted_tokens', 'token_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_blacklisted_tokens_token_id'), 'blacklisted_tokens', ['token_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklisted_tokens_token_id'), table_name='blacklisted_tokens')
    op.alter_column('blacklisted_tokens', 'token_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
